name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.11.2'
       
     # Configure AWS credentials (from GitHub Secrets)
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    # Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # Run Terraform Plan
    - name: Terraform Plan
      run: terraform plan

    # Apply Terraform changes (be careful with this step in production)
    - name: Terraform Apply
      run: terraform apply -auto-approve
      # Add an approval step in production environments to avoid accidental changes


